// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SprawdzianSzymonLesnik.Data;

#nullable disable

namespace SprawdzianSzymonLesnik.Migrations
{
    [DbContext(typeof(SprawdzianSzymonLesnikContext))]
    [Migration("20241022074531_init2222")]
    partial class init2222
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SprawdzianSzymonLesnik.Models.Kurs", b =>
                {
                    b.Property<int>("KursId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KursId"));

                    b.Property<DateTime>("DataRozpoczecia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataZakonczenia")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NauczycielId1")
                        .HasColumnType("int");

                    b.Property<string>("NazwaKursu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KursId");

                    b.HasIndex("NauczycielId1");

                    b.ToTable("Kurs");
                });

            modelBuilder.Entity("SprawdzianSzymonLesnik.Models.Nauczyciel", b =>
                {
                    b.Property<int>("NauczycielId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NauczycielId"));

                    b.Property<string>("AdresZamieszkania")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NauczycielId");

                    b.ToTable("Nauczyciel");
                });

            modelBuilder.Entity("SprawdzianSzymonLesnik.Models.Uczen", b =>
                {
                    b.Property<int>("UczenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UczenId"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UczenId");

                    b.ToTable("Uczen");
                });

            modelBuilder.Entity("SprawdzianSzymonLesnik.Models.Kurs", b =>
                {
                    b.HasOne("SprawdzianSzymonLesnik.Models.Nauczyciel", "NauczycielId")
                        .WithMany()
                        .HasForeignKey("NauczycielId1");

                    b.Navigation("NauczycielId");
                });
#pragma warning restore 612, 618
        }
    }
}
